############## Created by de.microtema:github-workflow-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Files under .github/workflows folder are generated and should not be edited. #
################################################################################
name: 'Secure Password Exchange'
on:
  push:
    branches:
      - feature/*
env:
  APP_NAME: "secure-password-exchange"
  APP_DISPLAY_NAME: "Secure Password Exchange"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  NODE_VERSION: "16"
  VERSION: "1.0.0-SNAPSHOT"
jobs:
  versioning:
    name: Versioning
    runs-on: [ self-hosted ]
    needs: [ ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Node: Setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'NPM: versions'
        run: echo TBD
  
  compile:
    name: Compile
    runs-on: [ self-hosted ]
    needs: [ versioning ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Node: Setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'NPM: install'
        run: npm install --force
  
  security-check:
    name: Security Check
    runs-on: [ self-hosted ]
    needs: [ compile ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Node: Setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'NPM: install'
        run: npm install --force
      - name: 'NPM: security-check'
        run: npm run security-check
  unit-test:
    name: Unit Test
    runs-on: [ self-hosted ]
    needs: [ compile ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Node: Setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'NPM: install'
        run: npm install --force
      - name: 'NPM: test'
        run: npm test
  build:
    name: Build
    runs-on: [ self-hosted ]
    needs: [ unit-test ]
    env:
      BUILD_DIR: %BUILD_DIR%
      BUILD_APP_DIR: %BUILD_APP_DIR%
      STAGE_NAME: %STAGE_NAME%
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Node: Setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'NPM: install'
        run: npm install --force
      - name: 'NPM: build'
        run: npm run build:$STAGE_NAME
      - name: 'Artifact: prepare'
        run: |
          mkdir -p artifact/$BUILD_DIR
          cp -r $BUILD_DIR/* artifact/$BUILD_DIR/
      - name: 'Git: info'
        run: |
          echo '{ "commitId": "'${GITHUB_SHA}'", "branch": "${{ env.VERSION }}" }' > artifact/$BUILD_DIR/$BUILD_APP_DIR/git-info.json
      - name: 'Artifact: upload'
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: artifact
